"""empty message

Revision ID: 7908daa340d3
Revises: 
Create Date: 2022-03-13 03:47:59.390032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7908daa340d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('bedrooms', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('bathrooms', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('type', sa.Enum('house', 'apt', name='propertytype'), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('properties')
    # ### end Alembic commands ###
